CREATE TABLE ROUTE (
	ID			SERIAL,	
	ORIGIN 		VARCHAR,
	DESTINATION VARCHAR
);

CREATE TABLE  HISTORIC_SCORE(
	ID_ROUTE	INTEGER, 
	TIMESTAMP	TIMESTAMP WITHOUT TIME ZONE,
	SCORE 		DOUBLE PRECISION

);

DROP TABLE ROUTE;
DROP TABLE HISTORIC_SCORE;

