CREATE TABLE ROUTE (
	ID			SERIAL 	PRIMARY KEY,	
	ORIGIN 		VARCHAR NOT NULL,
	DESTINATION VARCHAR NOT NULL,
	CONSTRAINT UNIQUE_ORIGIN_DESTINATION UNIQUE (ORIGIN,DESTINATION)
);
CREATE INDEX ORIG_DEST_INDEX ON ROUTE (ORIGIN,DESTINATION);
CREATE TABLE HISTORIC_SCORE(
	ID_ROUTE	INTEGER 					NOT NULL, 
	TIMESTAMP	TIMESTAMP WITHOUT TIME ZONE NOT NULL,
	SCORE 		DOUBLE PRECISION 			NOT NULL,
	CONSTRAINT 	FK_ROUTE FOREIGN KEY (ID_ROUTE) REFERENCES ROUTE(ID)
	);

DROP TABLE HISTORIC_SCORE;
DROP INDEX ORIG_DEST_INDEX;
DROP TABLE ROUTE;

