CREATE TABLE ROUTE (
	ID			SERIAL 	PRIMARY KEY,	
	ORIGIN 		VARCHAR NOT NULL,
	DESTINATION VARCHAR NOT NULL,
	CONSTRAINT UNIQUE_ORIGIN_DESTINATION UNIQUE (ORIGIN,DESTINATION)
);
CREATE INDEX ORIG_DEST_INDEX ON ROUTE (ORIGIN,DESTINATION);
CREATE TABLE HISTORIC_SCORE(
	ROUTE_ID	INTEGER, 
	TIMESTAMP	TIMESTAMP WITHOUT TIME ZONE,
	SCORE 		DOUBLE PRECISION 			NOT NULL,
	CONSTRAINT  PK_HISTORIC_SCORE PRIMARY KEY (ROUTE_ID,TIMESTAMP),
	CONSTRAINT 	FK_ROUTE FOREIGN KEY (ROUTE_ID) REFERENCES ROUTE(ID)
	);

DROP TABLE HISTORIC_SCORE;
DROP INDEX ORIG_DEST_INDEX;
DROP TABLE ROUTE;


